name: jetter
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  meta: ^1.8.0
  collection: ^1.16.0
  http: ^0.13.5
  web_socket_channel: ^2.2.0
  path: ^1.8.2
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^2.0.0
  test: any
